In [0]:
!pip3 install newspaper3k

In [65]:
import requests
import re
from newspaper import Article
from bs4 import BeautifulSoup
bag_of_h=[]
def getText(url):
  url_= requests.get(url)
  soup= BeautifulSoup(url_.text, 'html.parser')
  get_h1=[i.get_text() for i in soup.find_all('h1')]
  get_h2=[j.get_text() for j in soup.find_all('h2')]
  get_h3=[k.get_text() for k in soup.find_all('h3')]
  
  for h in get_h1:
    bag_of_h.append(h)
  for j in get_h2:
    bag_of_h.append(j)
  for k in get_h3:
    bag_of_h.append(k)
  print(bag_of_h)

  
getText("http://fox13now.com/2013/12/30/new-year-new-laws-obamacare-pot-guns-and-drones/")

['New Year, new laws: Obamacare, pot, guns and\xa0drones', 'Like Fox 13 News on\xa0Facebook!', 'Email Alerts']


In [70]:
# import statments
import numpy
import re


def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

def word_extraction(sentence):
    ignore = ['a', "the", "is"]
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text    
    
def generate_bow(allsentences):    
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab));

    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w: 
                    bag_vector[i] += 1
                    
        print("{0} \n{1}\n".format(sentence,numpy.array(bag_vector)))
allsentences=bag_of_h
generate_bow(allsentences)


Word List for Document 
['13', 'alerts', 'and', 'drones', 'email', 'facebook', 'fox', 'guns', 'laws', 'like', 'new', 'news', 'obamacare', 'on', 'pot', 'year'] 

New Year, new laws: Obamacare, pot, guns and drones 
[0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 2. 0. 1. 0. 1. 1.]

Like Fox 13 News on Facebook! 
[1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0.]

Email Alerts 
[0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

